# Deployment whoami for ARM64
# https://hub.docker.com/r/stefanscherer/whoami
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kpcard-development
  name: hello-kubernetes
spec:
  selector:
    matchLabels:
      run: hello-kubernetes
  replicas: 3
  template:
    metadata:
      labels:
        run: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: stefanscherer/whoami:1.1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1280Mi"
            cpu: "1000m"
          requests:
            memory: "64Mi"
            cpu: "100m"
---        
apiVersion: v1
kind: Service
metadata:
  namespace: kpcard-development
  name: hello-kubernetes
  labels:
    run: hello-kubernetes
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: hello-kubernetes
